/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewsRouteImport } from './routes/news'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FarmersRouteImport } from './routes/farmers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommoditiesRouteImport } from './routes/commodities'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommoditiesSlugRouteImport } from './routes/commodities.$slug'

const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmersRoute = FarmersRouteImport.update({
  id: '/farmers',
  path: '/farmers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommoditiesRoute = CommoditiesRouteImport.update({
  id: '/commodities',
  path: '/commodities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommoditiesSlugRoute = CommoditiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CommoditiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commodities': typeof CommoditiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/farmers': typeof FarmersRoute
  '/insights': typeof InsightsRoute
  '/news': typeof NewsRoute
  '/commodities/$slug': typeof CommoditiesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commodities': typeof CommoditiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/farmers': typeof FarmersRoute
  '/insights': typeof InsightsRoute
  '/news': typeof NewsRoute
  '/commodities/$slug': typeof CommoditiesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commodities': typeof CommoditiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/farmers': typeof FarmersRoute
  '/insights': typeof InsightsRoute
  '/news': typeof NewsRoute
  '/commodities/$slug': typeof CommoditiesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/commodities'
    | '/contact'
    | '/farmers'
    | '/insights'
    | '/news'
    | '/commodities/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/commodities'
    | '/contact'
    | '/farmers'
    | '/insights'
    | '/news'
    | '/commodities/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/commodities'
    | '/contact'
    | '/farmers'
    | '/insights'
    | '/news'
    | '/commodities/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommoditiesRoute: typeof CommoditiesRouteWithChildren
  ContactRoute: typeof ContactRoute
  FarmersRoute: typeof FarmersRoute
  InsightsRoute: typeof InsightsRoute
  NewsRoute: typeof NewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmers': {
      id: '/farmers'
      path: '/farmers'
      fullPath: '/farmers'
      preLoaderRoute: typeof FarmersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commodities': {
      id: '/commodities'
      path: '/commodities'
      fullPath: '/commodities'
      preLoaderRoute: typeof CommoditiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commodities/$slug': {
      id: '/commodities/$slug'
      path: '/$slug'
      fullPath: '/commodities/$slug'
      preLoaderRoute: typeof CommoditiesSlugRouteImport
      parentRoute: typeof CommoditiesRoute
    }
  }
}

interface CommoditiesRouteChildren {
  CommoditiesSlugRoute: typeof CommoditiesSlugRoute
}

const CommoditiesRouteChildren: CommoditiesRouteChildren = {
  CommoditiesSlugRoute: CommoditiesSlugRoute,
}

const CommoditiesRouteWithChildren = CommoditiesRoute._addFileChildren(
  CommoditiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommoditiesRoute: CommoditiesRouteWithChildren,
  ContactRoute: ContactRoute,
  FarmersRoute: FarmersRoute,
  InsightsRoute: InsightsRoute,
  NewsRoute: NewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
